/**
 * 🔐 ENVIRONMENT MASTER - Security & Configuration Guardian
 * 
 * Node.js adaptation of Python EnvMaster
 * 
 * Features:
 * - Centralized environment variable tracking
 * - Auto-generate .env files with placeholders
 * - Security scanner for hardcoded secrets
 * - Environment validation and health checks
 * - Multi-environment support (dev, staging, prod)
 * 
 * Philosophy: Never commit secrets, always validate config
 */

const fs = require('fs');
const path = require('path');

class EnvMaster {
  constructor() {
    this.rootDir = process.cwd();
    this.envPath = path.join(this.rootDir, '.env');
    this.envTemplatePath = path.join(this.rootDir, '.env.template');
    
    // Required environment variables for n8.ked bot
    this.requiredVars = {
      // Discord Configuration
      DISCORD_TOKEN: {
        description: 'Discord bot token from Discord Developer Portal',
        required: true,
        sensitive: true,
        pattern: /^[A-Za-z0-9_\-\.]{50,}$/,
        example: 'MTQzMTE1MDMyMTU0Mjg5MzYyMw.XXXXXX.XXXXXXXXXXXXXXXXXXXXXX'
      },
      DISCORD_CLIENT_ID: {
        description: 'Discord application client ID',
        required: true,
        sensitive: false,
        pattern: /^\d{17,20}$/,
        example: '1431150321542893623'
      },
      
      // Twitch API Configuration
      TWITCH_CLIENT_ID: {
        description: 'Twitch application client ID',
        required: true,
        sensitive: false,
        pattern: /^[a-z0-9]{30}$/,
        example: 'xxxxxxxxxxxxxxxxxxxxxxxxxx'
      },
      TWITCH_CLIENT_SECRET: {
        description: 'Twitch application client secret',
        required: true,
        sensitive: true,
        pattern: /^[a-z0-9]{30}$/,
        example: 'xxxxxxxxxxxxxxxxxxxxxxxxxx'
      },
      
      // Database Configuration
      DATABASE_PATH: {
        description: 'Path to SQLite database file',
        required: false,
        sensitive: false,
        default: './database/n8ked.db',
        example: './database/n8ked.db'
      },
      
      // External API Keys
      USGS_API_KEY: {
        description: 'USGS Water Services API key (if required)',
        required: false,
        sensitive: true,
        pattern: /^[A-Za-z0-9\-]{20,}$/,
        example: 'your-usgs-api-key-here'
      },
      WEATHER_API_KEY: {
        description: 'Weather API key (OpenWeatherMap, WeatherAPI, etc)',
        required: false,
        sensitive: true,
        pattern: /^[A-Za-z0-9]{16,}$/,
        example: 'your-weather-api-key-here'
      },
      
      // YouTube API (Step 13)
      YOUTUBE_API_KEY: {
        description: 'YouTube Data API v3 key',
        required: false,
        sensitive: true,
        pattern: /^[A-Za-z0-9_\-]{39}$/,
        example: 'AIzaSyXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX'
      },
      
      // Twitter/X API (Step 13)
      TWITTER_API_KEY: {
        description: 'Twitter/X API key',
        required: false,
        sensitive: true,
        example: 'your-twitter-api-key'
      },
      TWITTER_API_SECRET: {
        description: 'Twitter/X API secret',
        required: false,
        sensitive: true,
        example: 'your-twitter-api-secret'
      },
      TWITTER_BEARER_TOKEN: {
        description: 'Twitter/X Bearer Token for API v2',
        required: false,
        sensitive: true,
        example: 'AAAAAAAAAAAAAAAAAAAAXXXXXXXXXXXXXXXXXXXX'
      },
      
      // Reddit API (Step 13)
      REDDIT_CLIENT_ID: {
        description: 'Reddit application client ID',
        required: false,
        sensitive: false,
        example: 'your-reddit-client-id'
      },
      REDDIT_CLIENT_SECRET: {
        description: 'Reddit application client secret',
        required: false,
        sensitive: true,
        example: 'your-reddit-client-secret'
      },
      
      // Environment & Features
      NODE_ENV: {
        description: 'Node environment (development, production, test)',
        required: false,
        sensitive: false,
        default: 'development',
        options: ['development', 'production', 'test'],
        example: 'development'
      },
      LOG_LEVEL: {
        description: 'Logging verbosity (error, warn, info, debug)',
        required: false,
        sensitive: false,
        default: 'info',
        options: ['error', 'warn', 'info', 'debug'],
        example: 'info'
      }
    };
  }
  
  /**
   * 📋 Generate .env.template file
   */
  generateTemplate() {
    let template = '# n8.ked Discord Bot - Environment Configuration\n';
    template += '# Generated by EnvMaster\n';
    template += `# Date: ${new Date().toISOString()}\n\n`;
    
    const categories = {
      'Discord Configuration': ['DISCORD_TOKEN', 'DISCORD_CLIENT_ID'],
      'Twitch Integration': ['TWITCH_CLIENT_ID', 'TWITCH_CLIENT_SECRET'],
      'Database': ['DATABASE_PATH'],
      'External APIs': ['USGS_API_KEY', 'WEATHER_API_KEY'],
      'Multi-Platform APIs (Step 13)': ['YOUTUBE_API_KEY', 'TWITTER_API_KEY', 'TWITTER_API_SECRET', 'TWITTER_BEARER_TOKEN', 'REDDIT_CLIENT_ID', 'REDDIT_CLIENT_SECRET'],
      'System Configuration': ['NODE_ENV', 'LOG_LEVEL']
    };
    
    for (const [category, vars] of Object.entries(categories)) {
      template += `# ═══════════════════════════════════════════\n`;
      template += `# ${category}\n`;
      template += `# ═══════════════════════════════════════════\n\n`;
      
      for (const varName of vars) {
        const config = this.requiredVars[varName];
        if (!config) continue;
        
        // Add description
        template += `# ${config.description}\n`;
        
        // Add options if available
        if (config.options) {
          template += `# Options: ${config.options.join(', ')}\n`;
        }
        
        // Add required status
        template += `# Required: ${config.required ? 'YES' : 'NO'}\n`;
        
        // Add variable with example or default
        const value = config.default || config.example || '';
        template += `${varName}=${value}\n\n`;
      }
    }
    
    template += '# ═══════════════════════════════════════════\n';
    template += '# Security Notes:\n';
    template += '# - NEVER commit .env files to version control\n';
    template += '# - Keep sensitive tokens secure\n';
    template += '# - Rotate credentials regularly\n';
    template += '# - Use environment-specific .env files\n';
    template += '# ═══════════════════════════════════════════\n';
    
    try {
      fs.writeFileSync(this.envTemplatePath, template);
      console.log(`✅ Generated .env.template at ${this.envTemplatePath}`);
      return true;
    } catch (error) {
      console.error('❌ Failed to generate template:', error.message);
      return false;
    }
  }
  
  /**
   * ✅ Validate current environment
   */
  validate() {
    const results = {
      valid: true,
      missing: [],
      invalid: [],
      warnings: [],
      configured: 0,
      total: 0
    };
    
    for (const [varName, config] of Object.entries(this.requiredVars)) {
      results.total++;
      const value = process.env[varName];
      
      // Check if required variable is missing
      if (config.required && !value) {
        results.missing.push(varName);
        results.valid = false;
        continue;
      }
      
      // If optional and not set, use default
      if (!value) {
        if (config.default) {
          process.env[varName] = config.default;
          results.configured++;
        }
        continue;
      }
      
      results.configured++;
      
      // Validate pattern if provided
      if (config.pattern && !config.pattern.test(value)) {
        results.invalid.push({
          var: varName,
          reason: `Does not match expected pattern`
        });
        results.warnings.push(`${varName} may be invalid (pattern mismatch)`);
      }
      
      // Validate options if provided
      if (config.options && !config.options.includes(value)) {
        results.invalid.push({
          var: varName,
          reason: `Must be one of: ${config.options.join(', ')}`
        });
        results.warnings.push(`${varName} = "${value}" (expected: ${config.options.join('/')})`);
      }
    }
    
    return results;
  }
  
  /**
   * 🔍 Scan codebase for hardcoded secrets
   */
  scanForSecrets() {
    const suspiciousPatterns = [
      { name: 'Discord Token', pattern: /[MN][A-Za-z\d]{23}\.[\w-]{6}\.[\w-]{27}/, severity: 'CRITICAL' },
      { name: 'Generic API Key', pattern: /[aA][pP][iI][_\-]?[kK][eE][yY]\s*[:=]\s*['"][^'"]{20,}['"]/, severity: 'HIGH' },
      { name: 'AWS Access Key', pattern: /AKIA[0-9A-Z]{16}/, severity: 'CRITICAL' },
      { name: 'Generic Secret', pattern: /[sS][eE][cC][rR][eE][tT]\s*[:=]\s*['"][^'"]{20,}['"]/, severity: 'HIGH' },
      { name: 'Password', pattern: /[pP][aA][sS][sS][wW][oO][rR][dD]\s*[:=]\s*['"][^'"]+['"]/, severity: 'MEDIUM' },
      { name: 'Bearer Token', pattern: /[bB]earer\s+[A-Za-z0-9\-_]+/, severity: 'HIGH' }
    ];
    
    const findings = [];
    const filesToScan = this.getJavaScriptFiles();
    
    for (const file of filesToScan) {
      try {
        const content = fs.readFileSync(file, 'utf8');
        const lines = content.split('\n');
        
        lines.forEach((line, index) => {
          for (const { name, pattern, severity } of suspiciousPatterns) {
            if (pattern.test(line)) {
              findings.push({
                file: path.relative(this.rootDir, file),
                line: index + 1,
                type: name,
                severity,
                snippet: line.trim().substring(0, 80)
              });
            }
          }
        });
      } catch (error) {
        // Skip files that can't be read
      }
    }
    
    return findings;
  }
  
  /**
   * 📁 Get all JavaScript files in project
   */
  getJavaScriptFiles(dir = this.rootDir, fileList = []) {
    const files = fs.readdirSync(dir);
    
    const ignoreDirs = ['node_modules', '.git', 'database/backups', 'past projects to integrate'];
    
    for (const file of files) {
      const filePath = path.join(dir, file);
      const stat = fs.statSync(filePath);
      
      if (stat.isDirectory()) {
        if (!ignoreDirs.includes(file)) {
          this.getJavaScriptFiles(filePath, fileList);
        }
      } else if (file.endsWith('.js')) {
        fileList.push(filePath);
      }
    }
    
    return fileList;
  }
  
  /**
   * 📊 Generate environment status report
   */
  getStatus() {
    const validation = this.validate();
    const secrets = this.scanForSecrets();
    
    const report = {
      environment: process.env.NODE_ENV || 'development',
      timestamp: new Date().toISOString(),
      validation,
      security: {
        secretsFound: secrets.length,
        criticalIssues: secrets.filter(s => s.severity === 'CRITICAL').length,
        findings: secrets
      },
      health: validation.valid && secrets.length === 0 ? 'HEALTHY' : 
              !validation.valid ? 'CRITICAL' : 
              secrets.length > 0 ? 'WARNING' : 'HEALTHY'
    };
    
    return report;
  }
  
  /**
   * 🎨 Format status report for Discord
   */
  formatStatusForDiscord() {
    const status = this.getStatus();
    
    let message = '```\n';
    message += '═══════════════════════════════════════════\n';
    message += '🔐 ENVIRONMENT STATUS\n';
    message += '═══════════════════════════════════════════\n\n';
    
    // Health indicator
    const healthEmoji = status.health === 'HEALTHY' ? '✅' : 
                        status.health === 'WARNING' ? '⚠️' : '❌';
    message += `Overall Health: ${healthEmoji} ${status.health}\n`;
    message += `Environment: ${status.environment}\n\n`;
    
    // Configuration status
    message += '📋 Configuration:\n';
    message += `  Configured: ${status.validation.configured}/${status.validation.total} variables\n`;
    
    if (status.validation.missing.length > 0) {
      message += `  ❌ Missing (${status.validation.missing.length}): ${status.validation.missing.join(', ')}\n`;
    }
    
    if (status.validation.warnings.length > 0) {
      message += `  ⚠️ Warnings:\n`;
      status.validation.warnings.forEach(w => {
        message += `     - ${w}\n`;
      });
    }
    
    // Security status
    message += '\n🔒 Security Scan:\n';
    if (status.security.secretsFound === 0) {
      message += '  ✅ No hardcoded secrets detected\n';
    } else {
      message += `  ⚠️ Found ${status.security.secretsFound} potential secrets\n`;
      message += `  🚨 Critical issues: ${status.security.criticalIssues}\n`;
      
      // Show first 3 findings
      const topFindings = status.security.findings.slice(0, 3);
      topFindings.forEach(f => {
        message += `     ${f.severity}: ${f.type} in ${f.file}:${f.line}\n`;
      });
      
      if (status.security.secretsFound > 3) {
        message += `     ... and ${status.security.secretsFound - 3} more\n`;
      }
    }
    
    message += '\n═══════════════════════════════════════════\n';
    message += '```';
    
    return message;
  }
  
  /**
   * 🛠️ Setup wizard for interactive configuration
   */
  async setupWizard() {
    console.log('🔐 n8.ked Environment Setup Wizard\n');
    
    // Check if .env exists
    if (fs.existsSync(this.envPath)) {
      console.log('⚠️  .env file already exists');
      console.log('   Backup will be created before modification\n');
      
      // Create backup
      const backupPath = `${this.envPath}.backup.${Date.now()}`;
      fs.copyFileSync(this.envPath, backupPath);
      console.log(`✅ Backup created: ${backupPath}\n`);
    }
    
    // Generate template
    this.generateTemplate();
    
    console.log('\n📋 Required Configuration:');
    console.log('   1. DISCORD_TOKEN - Get from https://discord.com/developers/applications');
    console.log('   2. DISCORD_CLIENT_ID - Same portal as above');
    console.log('   3. TWITCH_CLIENT_ID - Get from https://dev.twitch.tv/console');
    console.log('   4. TWITCH_CLIENT_SECRET - Same portal as above\n');
    
    console.log('📝 Next Steps:');
    console.log('   1. Copy .env.template to .env');
    console.log('   2. Fill in your API credentials');
    console.log('   3. Run !env_status to validate configuration');
    console.log('   4. Never commit .env to version control\n');
    
    return true;
  }
}

// Export singleton instance
const envMaster = new EnvMaster();

module.exports = envMaster;
